language: generic
sudo: required

git:
  depth: 1

matrix:
  include:
    - os: linux
      dist: bionic # ubuntu 18.04
    - os: linux
      dist: focal # ubuntu 20.04


script:
  -  |
    if [ $TRAVIS_DIST = "bionic" ] || [ $TRAVIS_DIST = "focal" ]; then
      ${TRAVIS_BUILD_DIR}/wg-ubuntu-server-up.sh
    fi
